---
# Home Assistant Glow
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# © Klaas Schoute
#
substitutions:
  device_name: home-assistant-glow
  friendly_name: Home Assistant Glow
  project_version: "5.0.0"
  device_description: "Measure your energy consumption with the pulse LED on your smart meter - ESP32-C3 Supermini"

  # Define the GPIO pins
  pulse_pin: GPIO4
  status_led: GPIO0
  led_pin_red: GPIO1
  led_pin_green: GPIO2

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "thomuk.home-assistant-glow-c3"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://ThomUK/home-assistant-glow-c3/esp32-c3-supermini.yaml@main

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

packages:
  remote_package:
    url: https://github.com/ThomUK/home-assistant-glow-c3/
    ref: "5.0.0"
    files:
      - components/basis.yaml
      - components/updates.yaml
      - components/status_led.yaml
      - components/pulse_meter.yaml

# Enable logging
logger:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap:
    ssid: '${friendly_name}'

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Local Web Server running on port 80
web_server:
  id: esphome_web_server
  version: 3
